const airportStands = {
    FACT: [
        { stand: 'A3', types: ['Heavy'] },
        { stand: 'A4', types: ['Heavy'] },
        { stand: 'A5', types: ['Heavy'] },
        { stand: 'A6', types: ['Heavy'] },
        { stand: 'A7', types: ['Heavy'] },
        { stand: 'A8', types: ['Heavy'] },
        { stand: 'A9', types: ['Medium'] },
        { stand: 'A10', types: ['Medium'] },
        { stand: 'A11', types: ['Medium'] },
        { stand: 'A12', types: ['Medium'] },
        { stand: 'A13', types: ['Medium'] },
        { stand: 'A14', types: ['Medium'] },
        { stand: 'A15', types: ['Medium'] },
        { stand: 'A16', types: ['Medium'] },
        { stand: 'A17', types: ['Medium'] },
        { stand: 'B1', types: ['Medium', 'Cargo', 'Light'] },
        { stand: 'B2', types: ['Medium', 'Cargo', 'Light'] },
        { stand: 'B3', types: ['Medium', 'Cargo', 'Light'] },
        { stand: 'B4', types: ['Medium', 'Cargo', 'Light'] },
        { stand: 'B5', types: ['Medium', 'Cargo', 'Light'] },
        { stand: 'B6', types: ['Medium', 'Cargo', 'Light'] },
        { stand: 'B7', types: ['Medium', 'Cargo', 'Light'] },
        { stand: 'B8', types: ['Medium', 'Cargo', 'Light'] },
        { stand: 'B9', types: ['Medium', 'Cargo', 'Light'] },
        { stand: 'B10', types: ['Medium', 'Cargo'] },
        { stand: 'B11', types: ['Medium', 'Cargo'] },
        { stand: 'B12', types: ['Medium', 'Cargo'] },
        { stand: 'B13', types: ['Medium', 'Cargo'] },
        { stand: 'B14', types: ['Medium', 'Cargo'] },
        { stand: 'B15', types: ['Medium', 'Cargo'] },
        { stand: 'B16', types: ['Medium'] },
        { stand: 'B17', types: ['Medium', 'Heavy'] },
        { stand: 'B18', types: ['Medium', 'Heavy'] },
        { stand: 'B19', types: ['Medium'] },
        { stand: 'B20', types: ['Medium'] },
        { stand: 'B21', types: ['Medium'] },
        { stand: 'B22', types: ['Medium'] },
        { stand: 'B23', types: ['Medium', 'Heavy'] },
        { stand: 'B24', types: ['Medium'] },
        { stand: 'B25', types: ['Medium'] },
        { stand: 'B26', types: ['Medium', 'Heavy'] },
        { stand: 'B27', types: ['Medium'] },
        { stand: 'B28', types: ['Medium'] },
        { stand: 'B29', types: ['Medium', 'Heavy'] },
        { stand: 'B30', types: ['Medium'] },
        { stand: 'B31', types: ['Medium'] },
        { stand: 'C1', types: ['Medium'] },
        { stand: 'C2', types: ['Medium'] },
        { stand: 'C3', types: ['Medium'] },
        { stand: 'C4', types: ['Medium'] },
        { stand: 'C5', types: ['Medium'] },
        { stand: 'Maintenance', types: ['Light', 'Medium', 'Heavy', 'Cargo'] },
        { stand: 'F1', types: ['Cargo'] },
        { stand: 'F2', types: ['Cargo'] },
        { stand: 'Freight Terminal', types: ['Cargo'] },
        // Add more stands with respective aircraft types here
    ],
    FAOR: [
        { stand: 'A1', types: ['Heavy'] },
        { stand: 'A1R', types: ['Heavy'] },
        { stand: 'A2', types: ['Heavy'] },
        { stand: 'A3', types: ['Heavy'] },
        { stand: 'A4', types: ['Heavy'] },
        { stand: 'A5', types: ['Heavy'] },
        { stand: 'A6', types: ['Heavy'] },
        { stand: 'A7', types: ['Heavy'] },
        { stand: 'A8', types: ['Heavy'] },
        { stand: 'A9', types: ['Medium'] },
        { stand: 'A10', types: ['Medium'] },
        { stand: 'A11', types: ['Medium'] },
        { stand: 'A12', types: ['Medium'] },
        { stand: 'A13', types: ['Medium'] },
        { stand: 'B1', types: ['Light', 'Medium'] },
        { stand: 'B2', types: ['Light', 'Medium'] },
        { stand: 'B3', types: ['Light', 'Medium'] },
        { stand: 'B4', types: ['Light', 'Medium'] },
        { stand: 'B5', types: ['Light', 'Medium'] },
        { stand: 'B6', types: ['Light', 'Medium'] },
        { stand: 'B7', types: ['Light', 'Medium'] },
        { stand: 'B8', types: ['Light', 'Medium'] },
        { stand: 'B9', types: ['Light', 'Medium'] },
        { stand: 'B10', types: ['Light', 'Medium'] },
        { stand: 'B11', types: ['Light', 'Medium'] },
        { stand: 'B12', types: ['Light', 'Medium'] },
        { stand: 'B13', types: ['Light', 'Medium'] },
        { stand: 'C1', types: ['Medium'] },
        { stand: 'C2', types: ['Medium'] },
        { stand: 'C3', types: ['Medium'] },
        { stand: 'C4', types: ['Medium'] },
        { stand: 'C5', types: ['Medium'] },
        { stand: 'C6', types: ['Medium'] },
        { stand: 'C7', types: ['Medium'] },
        { stand: 'C8', types: ['Medium'] },
        { stand: 'C9', types: ['Medium'] },
        { stand: 'C10', types: ['Medium'] },
        { stand: 'C11', types: ['Medium'] },
        { stand: 'C12', types: ['Medium'] },
        { stand: 'C13', types: ['Medium'] },
        { stand: 'C14', types: ['Medium'] },
        { stand: 'C15', types: ['Medium'] },
        { stand: 'C16', types: ['Medium'] },
        { stand: 'C17', types: ['Medium'] },
        { stand: 'C18', types: ['Light', 'Medium'] },
        { stand: 'C19', types: ['Light', 'Medium'] },
        { stand: 'C20', types: ['Light', 'Medium'] },
        { stand: 'C21', types: ['Light', 'Medium'] },
        { stand: 'C22', types: ['Light', 'Medium'] },
        { stand: 'C23', types: ['Light', 'Medium'] },
        { stand: 'C24', types: ['Light', 'Medium'] },
        { stand: 'D1L', types: ['Cargo'] },
        { stand: 'D1', types: ['Cargo'] },
        { stand: 'D1R', types: ['Cargo'] },
        { stand: 'D2L', types: ['Cargo'] },
        { stand: 'D2', types: ['Cargo'] },
        { stand: 'D2R', types: ['Cargo'] },
        { stand: 'D3L', types: ['Cargo'] },
        { stand: 'D3', types: ['Cargo'] },
        { stand: 'D3R', types: ['Cargo'] },
        { stand: 'D4L', types: ['Cargo'] },
        { stand: 'D4', types: ['Cargo'] },
        { stand: 'D4R', types: ['Cargo'] },
        { stand: 'D5', types: ['Cargo'] },
        { stand: 'D6', types: ['Cargo'] },
        { stand: 'D7', types: ['Cargo'] },
        { stand: 'D8', types: ['Cargo'] },
        { stand: 'D9', types: ['Cargo'] },
        { stand: 'D10', types: ['Cargo'] },
        { stand: 'D11', types: ['Cargo'] },
        { stand: 'D12', types: ['Cargo'] },
        { stand: 'D13', types: ['Cargo'] },
        { stand: 'D14', types: ['Cargo'] },
        { stand: 'D15', types: ['Cargo'] },
        { stand: 'D16', types: ['Cargo'] },
        { stand: 'D17', types: ['Cargo'] },
        { stand: 'D18', types: ['Cargo'] },
        { stand: 'D19', types: ['Cargo'] },
        { stand: 'D20', types: ['Cargo'] },
        { stand: 'D21', types: ['Cargo'] },
        { stand: 'D22', types: ['Cargo'] },
        { stand: 'D23', types: ['Cargo'] },
        { stand: 'D24', types: ['Cargo'] },
        { stand: 'D25', types: ['Cargo'] },
        { stand: 'D26', types: ['Cargo'] },
        { stand: 'D27', types: ['Cargo'] },
        { stand: 'D28', types: ['Cargo'] },
        { stand: 'D29', types: ['Cargo'] },
        { stand: 'D30', types: ['Cargo'] },
        { stand: 'D31', types: ['Cargo'] },
        { stand: 'D32', types: ['Cargo'] },
        { stand: 'D33', types: ['Cargo'] },
        { stand: 'D34', types: ['Cargo'] },
        { stand: 'D35', types: ['Cargo'] },
        { stand: 'D36', types: ['Cargo'] },
        { stand: 'D37', types: ['Cargo'] },
        { stand: 'D38', types: ['Cargo'] },
        { stand: 'D39', types: ['Cargo'] },
        { stand: 'D40', types: ['Cargo'] },
        { stand: 'D41', types: ['Cargo'] },
        { stand: 'D42', types: ['Cargo'] },
        { stand: 'D43', types: ['Cargo'] },
        { stand: 'D44', types: ['Cargo'] },
        { stand: 'D45', types: ['Cargo'] },
        { stand: 'D46', types: ['Cargo'] },
        { stand: 'D47', types: ['Cargo'] },
        { stand: 'D48', types: ['Cargo'] },
        { stand: 'D49', types: ['Cargo'] },
        { stand: 'D50', types: ['Cargo'] },
        { stand: 'D66', types: ['Cargo'] },
        { stand: 'D77', types: ['Cargo'] },
        { stand: 'E1', types: ['Heavy'] },
        { stand: 'E2', types: ['Medium'] },
        { stand: 'E3', types: ['Heavy'] },
        { stand: 'E4', types: ['Medium'] },
        { stand: 'E5', types: ['Medium'] },
        { stand: 'E6', types: ['Heavy'] },
        { stand: 'E7', types: ['Medium'] },
        { stand: 'E8', types: ['Medium'] },
        { stand: 'E9', types: ['Heavy'] },
        { stand: 'E10', types: ['Medium'] },
        { stand: 'E11', types: ['Medium'] },
        { stand: 'E12', types: ['Heavy'] },
        { stand: 'E13', types: ['Medium'] },
        { stand: 'F1', types: ['Heavy'] },
        { stand: 'F2', types: ['Medium'] },
        { stand: 'F3', types: ['Heavy'] },
        { stand: 'F4', types: ['Medium'] },
        { stand: 'F5', types: ['Medium'] },
        { stand: 'F6', types: ['Heavy'] },
        { stand: 'F7', types: ['Medium'] },
        { stand: 'G1', types: ['Cargo'] },
        { stand: 'G2', types: ['Cargo'] },
        { stand: 'G3', types: ['Cargo'] },
        { stand: 'G4', types: ['Cargo'] },
        { stand: 'G5', types: ['Cargo'] },
        { stand: 'G6', types: ['Cargo'] },
        { stand: 'G7', types: ['Cargo'] },
        // Add more FAOR stands here
    ],
    // Add other airports like FAPE, FAGG, FALA here
FALE: [
    { stand: 'A1', types: ['Light', 'Medium', 'Cargo'] },
    { stand: 'A2', types: ['Light', 'Medium', 'Cargo'] },
    { stand: 'A3', types: ['Light', 'Medium', 'Cargo'] },
    { stand: 'A4', types: ['Light', 'Medium', 'Cargo'] },
    { stand: 'A5', types: ['Medium'] },
    { stand: 'A6', types: ['Medium'] },
    { stand: 'A7', types: ['Medium'] },
    { stand: 'A8', types: ['Medium'] },
    { stand: 'A9', types: ['Medium'] },
    { stand: 'A10', types: ['Medium'] },
    { stand: 'A11', types: ['Medium'] },
    { stand: 'A12', types: ['Medium'] },
    { stand: 'A13', types: ['Medium'] },
    { stand: 'A14', types: ['Medium'] },
    { stand: 'A15', types: ['Medium'] },
    { stand: 'A16', types: ['Medium'] },
    { stand: 'B1', types: ['Light', 'Medium', 'Cargo'] },
    { stand: 'B2', types: ['Light', 'Medium', 'Cargo'] },
    { stand: 'B3', types: ['Light', 'Medium', 'Cargo'] },
    { stand: 'B4', types: ['Light', 'Medium', 'Cargo'] },
    { stand: 'B5', types: ['Light', 'Medium', 'Cargo'] },
    { stand: 'B6', types: ['Light', 'Medium', 'Cargo'] },
    { stand: 'B7', types: ['Light', 'Medium', 'Cargo'] },
    { stand: 'B8', types: ['Light', 'Medium', 'Cargo'] },
    { stand: 'B9', types: ['Light', 'Medium', 'Cargo'] },
    { stand: 'C1', types: ['Medium'] },
    { stand: 'C2', types: ['Heavy'] },
    { stand: 'C3', types: ['Heavy'] },
    { stand: 'C4', types: ['Medium'] },
    { stand: 'C5', types: ['Heavy'] },
    { stand: 'C6', types: ['Heavy'] },
    { stand: 'D1', types: ['Cargo', 'Heavy'] },
    { stand: 'D2', types: ['Cargo', 'Heavy'] },
    { stand: 'D3', types: ['Cargo', 'Heavy'] },
    { stand: 'D4', types: ['Cargo', 'Heavy'] },
    { stand: 'D5', types: ['Cargo', 'Heavy'] },
    { stand: 'D6', types: ['Cargo', 'Heavy'] },
],  

FAPE: [
    { stand: 'A1', types: ['Cargo', 'Medium'] },
    { stand: 'A2', types: ['Cargo', 'Medium'] },
    { stand: 'A3', types: ['Cargo', 'Medium'] },
    { stand: 'A4', types: ['Cargo', 'Medium'] },
    { stand: 'A5', types: ['Cargo', 'Medium'] },
    { stand: 'A6', types: ['Cargo', 'Medium'] },
    { stand: 'A7', types: ['Cargo', 'Medium'] },
    { stand: 'A8', types: ['Cargo', 'Medium'] },
    { stand: 'A9', types: ['Cargo', 'Medium'] },
    { stand: 'A10', types: ['Cargo', 'Medium'] },
    { stand: 'A10A', types: ['Cargo', 'Medium'] },
    { stand: 'A11', types: ['Cargo', 'Medium'] },
    { stand: 'A12', types: ['Cargo', 'Medium'] },   
],

FAGG:[
    { stand: 'A1', types: ['Cargo', 'Medium'] },
    { stand: 'A2', types: ['Cargo', 'Medium'] }, 
    { stand: 'A3', types: ['Cargo', 'Medium'] }, 
    { stand: 'A4', types: ['Cargo', 'Medium'] }, 
    { stand: 'A5', types: ['Cargo', 'Medium'] }, 
    { stand: 'A6', types: ['Cargo', 'Medium'] },  

],

FAEL:[
    { stand: '1', types: ['Light', 'Cargo', 'Medium'] },
    { stand: '2', types: ['Light', 'Cargo', 'Medium'] },  
    { stand: '3', types: ['Light', 'Cargo', 'Medium'] },  
    { stand: '4', types: ['Light', 'Cargo', 'Medium'] },  
    { stand: '5', types: ['Light', 'Cargo', 'Medium'] },    
    { stand: '6', types: ['Light', 'Cargo', 'Medium'] },  

],

FAUP:[
    { stand: '1', types: ['Light', 'Cargo', 'Medium'] },
    { stand: '2', types: ['Light', 'Cargo', 'Medium'] },
    { stand: '3', types: ['Light', 'Cargo', 'Medium'] },
    { stand: '4', types: ['Light', 'Cargo', 'Medium'] },
],

FALA:[
    { stand: 'A1L', types: ['Light', 'Cargo', 'Medium'] },
    { stand: 'A1', types: ['Light', 'Cargo', 'Medium'] },
    { stand: 'A1R', types: ['Light', 'Cargo', 'Medium'] },
    { stand: 'A2L', types: ['Light', 'Cargo', 'Medium'] },
    { stand: 'A2', types: ['Light', 'Cargo', 'Medium'] },
    { stand: 'A2R', types: ['Light', 'Cargo', 'Medium'] },
    { stand: 'B1', types: ['Light', 'Cargo', 'Medium'] },
    { stand: 'B2', types: ['Light'] },
    { stand: 'B3', types: ['Light',] },
    { stand: 'B4', types: ['Light', 'Cargo', 'Medium'] },
    { stand: 'B5', types: ['Light'] },
    { stand: 'B6', types: ['Light'] },
    { stand: 'B7', types: ['Light', 'Cargo', 'Medium'] },
    { stand: 'B8', types: ['Light', 'Cargo', 'Medium'] },
    { stand: 'B9', types: ['Light', 'Cargo', 'Medium'] },
    { stand: 'B10', types: ['Light', 'Cargo', 'Medium'] },
    { stand: 'C1L', types: ['Light'] },
    { stand: 'C1', types: ['Light', 'Cargo', 'Medium'] },
    { stand: 'C1R', types: ['Light'] },
    { stand: 'C2L', types: ['Light'] },
    { stand: 'C2', types: ['Light', 'Cargo', 'Medium'] },
    { stand: 'C2R', types: ['Light'] },
    { stand: 'C3L', types: ['Light'] },
    { stand: 'C3', types: ['Light', 'Cargo', 'Medium'] },
    { stand: 'C3R', types: ['Light'] },
    { stand: 'C4L', types: ['Light'] },
    { stand: 'C4', types: ['Light', 'Cargo', 'Medium'] },
    { stand: 'C4R', types: ['Light'] },
    { stand: 'C5R', types: ['Light'] },
    { stand: 'C5', types: ['Light', 'Cargo', 'Medium'] },
    { stand: 'C6', types: ['Light', 'Cargo', 'Medium'] },
    { stand: 'C7L', types: ['Light'] },
    { stand: 'C7', types: ['Light', 'Cargo', 'Medium'] },
    { stand: 'C7R', types: ['Light'] },
    { stand: 'C8L', types: ['Light'] },
    { stand: 'C8', types: ['Light', 'Cargo', 'Medium'] },

],

FAKN:[
    { stand: 'A1', types: ['Light', 'Cargo', 'Medium'] },
    { stand: 'A2', types: ['Light', 'Cargo', 'Medium'] },
    { stand: 'A3', types: ['Light', 'Cargo', 'Medium'] },
    { stand: 'A4', types: ['Light', 'Cargo', 'Medium'] },
    { stand: 'B1', types: ['Light'] },
    { stand: 'B2', types: ['Light'] },
    { stand: 'B3', types: ['Light'] },
    { stand: 'C1', types: ['Light'] },
    { stand: 'C2', types: ['Light'] },
    { stand: 'C3', types: ['Light'] },
    { stand: 'D1', types: ['Light'] },
    { stand: 'D2', types: ['Light'] },
    { stand: 'D3', types: ['Light'] },

],

FAGM:[
    { stand: '1', types: ['Light'] },
    { stand: '2', types: ['Light'] },
    { stand: '3', types: ['Light'] },
    { stand: '4', types: ['Light'] },
    { stand: '5', types: ['Light'] },
    { stand: '6', types: ['Light'] },
    { stand: '7', types: ['Light'] },
    { stand: '8', types: ['Light'] },
]
};

function assignStand(icao, aircraftType) {
    const stands = airportStands[icao] || [];
    const availableStands = stands.filter(stand => stand.types.includes(aircraftType));

    if (availableStands.length > 0) {
        const randomStand = availableStands[Math.floor(Math.random() * availableStands.length)];
        return randomStand.stand;
    } else {
        return 'No stands available for this type';
    }
}

document.getElementById('assignStandBtn').addEventListener('click', function() {
    const icao = document.getElementById('icaoCode').value;
    const aircraftType = document.getElementById('aircraftType').value;
    const assignedStand = assignStand(icao, aircraftType);
    document.getElementById('standResult').innerText = `Assigned Stand: ${assignedStand}`;
});
